# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, $terminal -e lazydocker
bindd = SUPER SHIFT, G, Gmail, exec, omarchy-launch-webapp "https://mail.google.com"

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER SHIFT, L, Whisper STT, exec, $HOME/.config/whisper-stt/toggle-recording.sh

# Overwrite existing bindings
bindd = SUPER SHIFT, P, Screenshot with Editing, exec, omarchy-cmd-screenshot
bindd = SUPER SHIFT, V, Screenrecording, exec, omarchy-menu screenrecord
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-webapp "https://app.todoist.com/app/today"
bindd = SUPER SHIFT, E, Activity, exec, omarchy-launch-or-focus evolution
